In [11]:
import pandas as pd
import numpy as np
df_pmi = pd.read_csv(r"C:\Users\KHATERINE\PACMANN\PLBI\PLBI\Laporan Gudang Darurat PMI (s.d. 27 April 2021).csv")
df_pmi = df_pmi[df_pmi["Tanggal"].notna()]
df_pmi

,Tanggal,IN / OUT,Nomor GDN/GRN,Gudang,Dari/Kepada-Masking,Nama Barang,Merk/Jenis-Deleted,Satuan,Masuk,Keluar,Nilai,Jumlah,Berat,Total Berat
0,01-Feb-20,IN,1.01,G2,Gudang Regional PMI_Serang,Masker Bedah,Sensi,Pcs,"350,000",NaN,"Rp7,000","Rp2,450,000,000",0.006,2100.00
1,01-Feb-20,OUT,1.01,G2,Ketua Umum,Masker N95,3M,Pcs,NaN,800,"Rp108,240","Rp86,592,000",0.04,32.00
2,01-Feb-20,OUT,1.02,G2,PMI Kabupaten Natuna,Masker Bedah,Sensi,Pcs,NaN,"20,000","Rp7,000","Rp140,000,000",0.006,120.00
3,05-Feb-20,OUT,5.01,G2,Palang Merah Hongkong,Masker Bedah,Sensi,Pcs,NaN,"50,000","Rp7,000","Rp350,000,000",0.006,300.00
4,05-Feb-20,OUT,5.02,G2,Lain-lain,Masker Bedah,Sensi,Pcs,NaN,"4,000","Rp7,000","Rp28,000,000",0.006,24.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8184,26-Apr-21,OUT,-,G4,Tidak Layak digunakan (Reject),Kopi Kapal Api,NaN,Pcs,NaN,10,NaN,Rp-,NaN,0.00
8185,26-Apr-21,OUT,-,G4,Tidak Layak digunakan (Reject),Mie Instan,NaN,Pcs,NaN,9,NaN,Rp-,NaN,0.00
8186,26-Apr-21,OUT,-,G4,Tidak Layak digunakan (Reject),Cheetos Snack 15 g,NaN,Pcs,NaN,46,NaN,Rp-,NaN,0.00
8187,27-Apr-21,OUT,27.01,G4,Staff MP PMI,Wipol,NaN,Pouch,NaN,2,"Rp15,500","Rp31,000",0.78,1.56
8188,27-Apr-21,OUT,27.01,G4,Staff MP PMI,Sabun Marina,NaN,Pouch,NaN,2,"Rp20,000","Rp40,000",0.43,0.86